steps:

  - label: ':test_tube: Testing'
    command: './scripts/run-unit-test.sh'
    agents: 
      queue: fma-dev
      
  - label: ":SonarQube: Run SonarQube scan"
    command: ./.sonarqube/scan.sh
    agents:
      queue: "fma-dev"

  - block

  - label: ':cloudsmith: Build image and push to Cloudsmith'
    command: './scripts/build-and-publish-to-cloudsmith.sh'
    agents:
      queue: fma-dev
      
  - wait
  
  - label: ":k8s: Deploy to Europa Pre-Prod"
    command: './scripts/deploy.sh'
    agents:
      queue: europa-preprod-fma