steps:
  - label: 'do not panic :cherry_blossom::whale:'
    command: 'echo hello, engineer'
    agents:
      queue: fma-dev

  - wait

  - label: '"test_tube: Testing'
    command: '../scripts/run-unit-test.sh'
    agents: 
      queue: fma-dev